I agree
Co-Authored-By: mauricio-riquelme <40346835+mauricio-riquelme@users.noreply.github.com>

diff --git a/lib/githooks/pre-commit b/lib/githooks/pre-commit
--- a/lib/githooks/pre-commit
+++ b/lib/githooks/pre-commit
@@ -1,5 +1,11 @@
 #!/bin/bash
 # shellcheck disable=SC2039
+usage()
+{
+  echo "Usage : $0 <files>"
+  echo "${2}" # The error message
+  exit "${1:-0}"
+}
 
 set -uo pipefail
 
